#!/bin/sh

ADDONNAME=hm-tools
ADDON_DIR=/usr/local/addons/hm-tools
PROFILE_DIR=/usr/local/etc/profile.d
WWW_DIR=/usr/local/etc/config/addons/www/hm-tools
# CONFIG_URL=/addons/hm-tools/

case "$1" in
""|start)
  ;;
info)
  echo "Info: <b>HM-Tools CCU Addon</b><br>"
  echo "Info: Kommandozeilentools<br>"
  echo "Info: OpenCCU/RaspberryMatic; arm, aarch64 und x86<br>"
  echo "Info: <br>"
  echo "Info: (c) 2023 Frank Hettrich; Pi5/CM5 fork WolfHenk<br>"
  echo "Info: <a href='https://github.com/WolfHenk/hm-tools'>https://github.com/WolfHenk/hm-tools</a>"
  echo "Version: $(cat ${ADDON_DIR}/VERSION)"
  echo "Name: HM-Tools<br>"
  echo "Operations: uninstall"
  echo "Update: /addons/${ADDONNAME}/update-check.cgi"
  ;;
uninstall)
  rm -rf "${ADDON_DIR}"
  rm -rf "${WWW_DIR}"
  rm -f "${PROFILE_DIR}/hm-tools-addons.sh"
  ;;
esac

exit 0
